### ISSUE TITLE
expand source definition of an application

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/nulecule#37]
We had a brief chat with @vpavlin and @kbsingh today.
It could be great if application source could be specified by:
- git url
- git branch
- path to source within git repo

Then the application could be built straight from sources (and e.g. fed into build system).

**Comment by goern** [comment]
That information could be provided by now using an URL like `https://github.com/goern/oh-my-vagrant/tree/feature/ansible_extra_vars/vagrant/docker`. But I see what you say: git url is mandatory, git branch is `master` if not set otherwise, path to source is `/` or the repository if not set otherwise.

Seems a reasonable extension of the spec.

**Comment by TomasTomecek** [comment]
And to follow up a bit, there could also be an application type in there:
- docker 
- appc
- ... 

Meaning, we would know that if the type is docker, we might expect a file called dockerfile and we would know, how to handle it.

**Comment by aweiteka** [comment]
There's also the `curl` or `wget` style of pulling in remote files such as https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/examples/pod.yaml

I'm not sure we call out the various protocols supported.

**Comment by aweiteka** [comment]
Resolved by https://github.com/projectatomic/nulecule/pull/74
